### ISSUE TITLE
"make build/vm/ubuntu" failed

### ISSUE THREAD

**Issue by ruschein** [gyf304/vmcli#1]
After replacing id_rsa.pub w/ id_ecdsa.pub, I ran "make build/vm/ubuntu" which downloaded a bunch of stuff and eventually failed w/:

(initramfs) [6ndd: invalid number: '1m'

**Comment by gyf304** [comment]
Would you mind posting your modified `vmbuilders/ubuntu.sh`?

**Comment by heywoodlh** [comment]
I ran into this same issue. My problem is that I am using `nix` as my package manager which is using the GNU version of `dd` instead of the FreeBSD version. 

```bash
~ $ which dd
/etc/profiles/per-user/heywoodlh/bin/dd
```

The FreeBSD version of `dd` uses lower case letters for the block size (i.e. `1m`) vs the GNU version using caps (`1M`). 

I fixed my issue by modifying `vmbuilders/ubuntu.sh` to point to the MacOS-included `/bin/dd`:

```bash
# expand disk to 4GB
/bin/dd if=/dev/null of=disk.img bs=1m count=0 seek="$disk_size"
```

On a related note: I also had to modify `vmbuilders/ubuntu.sh` to use `/usr/bin/uname` instead of the `uname` in my PATH because Nix included an x86_64 version of `uname` so `vmbuilders/ubuntu.sh` was grabbing the x86_64 bit version of Ubuntu vs the arm64 version.


Maybe a fix for this would be to point the tools reliant on the included MacOS binaries by using their full path rather than relying on the user's $PATH to find those commands. I can submit a pull request if desired?

**Comment by gyf304** [comment]
@heywoodlh That'd be great!

**Comment by gyf304** [comment]
Thanks @heywoodlh !

**Comment by ruschein** [comment]
I second that: thanks @heywoodlh using the explicit paths for dd and uname also fixed my problem.  I have the GNU binutils from MacPorts installed.
